[toolchain]
anchor_version = "0.32.1"

[features]
default = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
seeds = false
skip-lint = true

[programs.localnet]
solana_tdp = "6VkmhxbTH9dnzAE7Scpxn6R3HeXYtY4oZffAFMAYvECk"

[programs.devnet]
solana_tdp = "6VkmhxbTH9dnzAE7Scpxn6R3HeXYtY4oZffAFMAYvECk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./keypairs/devnet-wallet.json"

[test]
# This helps when running 'anchor test' without a pre-started validator
startup_wait = 20000

[test.validator]
url = "http://127.0.0.1:8899"
rpc_port = 8899


[scripts]
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
