[toolchain]
anchor_version = "0.32.1"

[features]
resolution = true
skip-lint = true

[programs.devnet]
solana_tdp = "6VkmhxbTH9dnzAE7Scpxn6R3HeXYtY4oZffAFMAYvECk"

[programs.localnet]
solana_tdp = "6VkmhxbTH9dnzAE7Scpxn6R3HeXYtY4oZffAFMAYvECk"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "./keypairs/devnet-wallet.json"

[scripts]
test = "vitest run"

[test]
startup_wait = 20000
shutdown_wait = 2000
upgradeable = false
