packages:
  - "apps/*"
  - "packages/*"
nodeOptions: "--disable-warning=DEP0205"
allowBuilds:
  "@reown/appkit": true
  "@stellar/stellar-sdk": true
  bigint-buffer: true
  blake-hash: true
  bufferutil: true
  esbuild: true
  keccak: true
  protobufjs: true
  sharp: true
  tiny-secp256k1: true
  usb: true
  utf-8-validate: true
  workerd: true
minimumReleaseAgeExclude:
  - "@typescript/native-preview-darwin-arm64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-darwin-x64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-linux-arm64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-linux-arm@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-linux-x64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-win32-arm64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview-win32-x64@7.0.0-dev.20260618.1"
  - "@typescript/native-preview@7.0.0-dev.20260618.1"
