/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DocsRouteImport } from './routes/docs'
import { Route as AppRouteImport } from './routes/app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app.index'
import { Route as AppToolsRouteImport } from './routes/app.tools'
import { Route as AppSettingsRouteImport } from './routes/app.settings'
import { Route as AppProfileRouteImport } from './routes/app.profile'
import { Route as AppOrganizationsRouteImport } from './routes/app.organizations'
import { Route as AppHelpRouteImport } from './routes/app.help'
import { Route as AppCreateRouteImport } from './routes/app.create'
import { Route as AppAnalyticsRouteImport } from './routes/app.analytics'
import { Route as AppActivityRouteImport } from './routes/app.activity'
import { Route as AppToolsTokensRouteImport } from './routes/app.tools.tokens'
import { Route as AppToolsCreateTokenRouteImport } from './routes/app.tools.create-token'
import { Route as AppStreamsStreamPdaRouteImport } from './routes/app.streams.$streamPda'
import { Route as AppOrganizationsOrgIdRouteImport } from './routes/app.organizations.$orgId'
import { Route as AppCreateMilestoneRouteImport } from './routes/app.create.milestone'
import { Route as AppCreateLinearRouteImport } from './routes/app.create.linear'
import { Route as AppCreateCliffRouteImport } from './routes/app.create.cliff'
import { Route as AppToolsCreateTokenWalletRouteImport } from './routes/app.tools.create-token.wallet'
import { Route as AppToolsCreateTokenPlatformRouteImport } from './routes/app.tools.create-token.platform'
import { Route as AppOrganizationsOrgIdEditRouteImport } from './routes/app.organizations.$orgId.edit'

const DocsRoute = DocsRouteImport.update({
  id: '/docs',
  path: '/docs',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsRoute = AppToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsRoute = AppOrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => AppRoute,
} as any)
const AppHelpRoute = AppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AppRoute,
} as any)
const AppCreateRoute = AppCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)
const AppActivityRoute = AppActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => AppRoute,
} as any)
const AppToolsTokensRoute = AppToolsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppToolsCreateTokenRoute = AppToolsCreateTokenRouteImport.update({
  id: '/create-token',
  path: '/create-token',
  getParentRoute: () => AppToolsRoute,
} as any)
const AppStreamsStreamPdaRoute = AppStreamsStreamPdaRouteImport.update({
  id: '/streams/$streamPda',
  path: '/streams/$streamPda',
  getParentRoute: () => AppRoute,
} as any)
const AppOrganizationsOrgIdRoute = AppOrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => AppOrganizationsRoute,
} as any)
const AppCreateMilestoneRoute = AppCreateMilestoneRouteImport.update({
  id: '/milestone',
  path: '/milestone',
  getParentRoute: () => AppCreateRoute,
} as any)
const AppCreateLinearRoute = AppCreateLinearRouteImport.update({
  id: '/linear',
  path: '/linear',
  getParentRoute: () => AppCreateRoute,
} as any)
const AppCreateCliffRoute = AppCreateCliffRouteImport.update({
  id: '/cliff',
  path: '/cliff',
  getParentRoute: () => AppCreateRoute,
} as any)
const AppToolsCreateTokenWalletRoute =
  AppToolsCreateTokenWalletRouteImport.update({
    id: '/wallet',
    path: '/wallet',
    getParentRoute: () => AppToolsCreateTokenRoute,
  } as any)
const AppToolsCreateTokenPlatformRoute =
  AppToolsCreateTokenPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => AppToolsCreateTokenRoute,
  } as any)
const AppOrganizationsOrgIdEditRoute =
  AppOrganizationsOrgIdEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AppOrganizationsOrgIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/create': typeof AppCreateRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tools': typeof AppToolsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/create/cliff': typeof AppCreateCliffRoute
  '/app/create/linear': typeof AppCreateLinearRoute
  '/app/create/milestone': typeof AppCreateMilestoneRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/app/streams/$streamPda': typeof AppStreamsStreamPdaRoute
  '/app/tools/create-token': typeof AppToolsCreateTokenRouteWithChildren
  '/app/tools/tokens': typeof AppToolsTokensRoute
  '/app/organizations/$orgId/edit': typeof AppOrganizationsOrgIdEditRoute
  '/app/tools/create-token/platform': typeof AppToolsCreateTokenPlatformRoute
  '/app/tools/create-token/wallet': typeof AppToolsCreateTokenWalletRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/docs': typeof DocsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/create': typeof AppCreateRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tools': typeof AppToolsRouteWithChildren
  '/app': typeof AppIndexRoute
  '/app/create/cliff': typeof AppCreateCliffRoute
  '/app/create/linear': typeof AppCreateLinearRoute
  '/app/create/milestone': typeof AppCreateMilestoneRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/app/streams/$streamPda': typeof AppStreamsStreamPdaRoute
  '/app/tools/create-token': typeof AppToolsCreateTokenRouteWithChildren
  '/app/tools/tokens': typeof AppToolsTokensRoute
  '/app/organizations/$orgId/edit': typeof AppOrganizationsOrgIdEditRoute
  '/app/tools/create-token/platform': typeof AppToolsCreateTokenPlatformRoute
  '/app/tools/create-token/wallet': typeof AppToolsCreateTokenWalletRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteWithChildren
  '/docs': typeof DocsRoute
  '/app/activity': typeof AppActivityRoute
  '/app/analytics': typeof AppAnalyticsRoute
  '/app/create': typeof AppCreateRouteWithChildren
  '/app/help': typeof AppHelpRoute
  '/app/organizations': typeof AppOrganizationsRouteWithChildren
  '/app/profile': typeof AppProfileRoute
  '/app/settings': typeof AppSettingsRoute
  '/app/tools': typeof AppToolsRouteWithChildren
  '/app/': typeof AppIndexRoute
  '/app/create/cliff': typeof AppCreateCliffRoute
  '/app/create/linear': typeof AppCreateLinearRoute
  '/app/create/milestone': typeof AppCreateMilestoneRoute
  '/app/organizations/$orgId': typeof AppOrganizationsOrgIdRouteWithChildren
  '/app/streams/$streamPda': typeof AppStreamsStreamPdaRoute
  '/app/tools/create-token': typeof AppToolsCreateTokenRouteWithChildren
  '/app/tools/tokens': typeof AppToolsTokensRoute
  '/app/organizations/$orgId/edit': typeof AppOrganizationsOrgIdEditRoute
  '/app/tools/create-token/platform': typeof AppToolsCreateTokenPlatformRoute
  '/app/tools/create-token/wallet': typeof AppToolsCreateTokenWalletRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/docs'
    | '/app/activity'
    | '/app/analytics'
    | '/app/create'
    | '/app/help'
    | '/app/organizations'
    | '/app/profile'
    | '/app/settings'
    | '/app/tools'
    | '/app/'
    | '/app/create/cliff'
    | '/app/create/linear'
    | '/app/create/milestone'
    | '/app/organizations/$orgId'
    | '/app/streams/$streamPda'
    | '/app/tools/create-token'
    | '/app/tools/tokens'
    | '/app/organizations/$orgId/edit'
    | '/app/tools/create-token/platform'
    | '/app/tools/create-token/wallet'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/docs'
    | '/app/activity'
    | '/app/analytics'
    | '/app/create'
    | '/app/help'
    | '/app/organizations'
    | '/app/profile'
    | '/app/settings'
    | '/app/tools'
    | '/app'
    | '/app/create/cliff'
    | '/app/create/linear'
    | '/app/create/milestone'
    | '/app/organizations/$orgId'
    | '/app/streams/$streamPda'
    | '/app/tools/create-token'
    | '/app/tools/tokens'
    | '/app/organizations/$orgId/edit'
    | '/app/tools/create-token/platform'
    | '/app/tools/create-token/wallet'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/docs'
    | '/app/activity'
    | '/app/analytics'
    | '/app/create'
    | '/app/help'
    | '/app/organizations'
    | '/app/profile'
    | '/app/settings'
    | '/app/tools'
    | '/app/'
    | '/app/create/cliff'
    | '/app/create/linear'
    | '/app/create/milestone'
    | '/app/organizations/$orgId'
    | '/app/streams/$streamPda'
    | '/app/tools/create-token'
    | '/app/tools/tokens'
    | '/app/organizations/$orgId/edit'
    | '/app/tools/create-token/platform'
    | '/app/tools/create-token/wallet'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  DocsRoute: typeof DocsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/docs': {
      id: '/docs'
      path: '/docs'
      fullPath: '/docs'
      preLoaderRoute: typeof DocsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools': {
      id: '/app/tools'
      path: '/tools'
      fullPath: '/app/tools'
      preLoaderRoute: typeof AppToolsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/settings': {
      id: '/app/settings'
      path: '/settings'
      fullPath: '/app/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/profile': {
      id: '/app/profile'
      path: '/profile'
      fullPath: '/app/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations': {
      id: '/app/organizations'
      path: '/organizations'
      fullPath: '/app/organizations'
      preLoaderRoute: typeof AppOrganizationsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/help': {
      id: '/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AppHelpRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/create': {
      id: '/app/create'
      path: '/create'
      fullPath: '/app/create'
      preLoaderRoute: typeof AppCreateRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/analytics': {
      id: '/app/analytics'
      path: '/analytics'
      fullPath: '/app/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/activity': {
      id: '/app/activity'
      path: '/activity'
      fullPath: '/app/activity'
      preLoaderRoute: typeof AppActivityRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/tools/tokens': {
      id: '/app/tools/tokens'
      path: '/tokens'
      fullPath: '/app/tools/tokens'
      preLoaderRoute: typeof AppToolsTokensRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/tools/create-token': {
      id: '/app/tools/create-token'
      path: '/create-token'
      fullPath: '/app/tools/create-token'
      preLoaderRoute: typeof AppToolsCreateTokenRouteImport
      parentRoute: typeof AppToolsRoute
    }
    '/app/streams/$streamPda': {
      id: '/app/streams/$streamPda'
      path: '/streams/$streamPda'
      fullPath: '/app/streams/$streamPda'
      preLoaderRoute: typeof AppStreamsStreamPdaRouteImport
      parentRoute: typeof AppRoute
    }
    '/app/organizations/$orgId': {
      id: '/app/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/app/organizations/$orgId'
      preLoaderRoute: typeof AppOrganizationsOrgIdRouteImport
      parentRoute: typeof AppOrganizationsRoute
    }
    '/app/create/milestone': {
      id: '/app/create/milestone'
      path: '/milestone'
      fullPath: '/app/create/milestone'
      preLoaderRoute: typeof AppCreateMilestoneRouteImport
      parentRoute: typeof AppCreateRoute
    }
    '/app/create/linear': {
      id: '/app/create/linear'
      path: '/linear'
      fullPath: '/app/create/linear'
      preLoaderRoute: typeof AppCreateLinearRouteImport
      parentRoute: typeof AppCreateRoute
    }
    '/app/create/cliff': {
      id: '/app/create/cliff'
      path: '/cliff'
      fullPath: '/app/create/cliff'
      preLoaderRoute: typeof AppCreateCliffRouteImport
      parentRoute: typeof AppCreateRoute
    }
    '/app/tools/create-token/wallet': {
      id: '/app/tools/create-token/wallet'
      path: '/wallet'
      fullPath: '/app/tools/create-token/wallet'
      preLoaderRoute: typeof AppToolsCreateTokenWalletRouteImport
      parentRoute: typeof AppToolsCreateTokenRoute
    }
    '/app/tools/create-token/platform': {
      id: '/app/tools/create-token/platform'
      path: '/platform'
      fullPath: '/app/tools/create-token/platform'
      preLoaderRoute: typeof AppToolsCreateTokenPlatformRouteImport
      parentRoute: typeof AppToolsCreateTokenRoute
    }
    '/app/organizations/$orgId/edit': {
      id: '/app/organizations/$orgId/edit'
      path: '/edit'
      fullPath: '/app/organizations/$orgId/edit'
      preLoaderRoute: typeof AppOrganizationsOrgIdEditRouteImport
      parentRoute: typeof AppOrganizationsOrgIdRoute
    }
  }
}

interface AppCreateRouteChildren {
  AppCreateCliffRoute: typeof AppCreateCliffRoute
  AppCreateLinearRoute: typeof AppCreateLinearRoute
  AppCreateMilestoneRoute: typeof AppCreateMilestoneRoute
}

const AppCreateRouteChildren: AppCreateRouteChildren = {
  AppCreateCliffRoute: AppCreateCliffRoute,
  AppCreateLinearRoute: AppCreateLinearRoute,
  AppCreateMilestoneRoute: AppCreateMilestoneRoute,
}

const AppCreateRouteWithChildren = AppCreateRoute._addFileChildren(
  AppCreateRouteChildren,
)

interface AppOrganizationsOrgIdRouteChildren {
  AppOrganizationsOrgIdEditRoute: typeof AppOrganizationsOrgIdEditRoute
}

const AppOrganizationsOrgIdRouteChildren: AppOrganizationsOrgIdRouteChildren = {
  AppOrganizationsOrgIdEditRoute: AppOrganizationsOrgIdEditRoute,
}

const AppOrganizationsOrgIdRouteWithChildren =
  AppOrganizationsOrgIdRoute._addFileChildren(
    AppOrganizationsOrgIdRouteChildren,
  )

interface AppOrganizationsRouteChildren {
  AppOrganizationsOrgIdRoute: typeof AppOrganizationsOrgIdRouteWithChildren
}

const AppOrganizationsRouteChildren: AppOrganizationsRouteChildren = {
  AppOrganizationsOrgIdRoute: AppOrganizationsOrgIdRouteWithChildren,
}

const AppOrganizationsRouteWithChildren =
  AppOrganizationsRoute._addFileChildren(AppOrganizationsRouteChildren)

interface AppToolsCreateTokenRouteChildren {
  AppToolsCreateTokenPlatformRoute: typeof AppToolsCreateTokenPlatformRoute
  AppToolsCreateTokenWalletRoute: typeof AppToolsCreateTokenWalletRoute
}

const AppToolsCreateTokenRouteChildren: AppToolsCreateTokenRouteChildren = {
  AppToolsCreateTokenPlatformRoute: AppToolsCreateTokenPlatformRoute,
  AppToolsCreateTokenWalletRoute: AppToolsCreateTokenWalletRoute,
}

const AppToolsCreateTokenRouteWithChildren =
  AppToolsCreateTokenRoute._addFileChildren(AppToolsCreateTokenRouteChildren)

interface AppToolsRouteChildren {
  AppToolsCreateTokenRoute: typeof AppToolsCreateTokenRouteWithChildren
  AppToolsTokensRoute: typeof AppToolsTokensRoute
}

const AppToolsRouteChildren: AppToolsRouteChildren = {
  AppToolsCreateTokenRoute: AppToolsCreateTokenRouteWithChildren,
  AppToolsTokensRoute: AppToolsTokensRoute,
}

const AppToolsRouteWithChildren = AppToolsRoute._addFileChildren(
  AppToolsRouteChildren,
)

interface AppRouteChildren {
  AppActivityRoute: typeof AppActivityRoute
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppCreateRoute: typeof AppCreateRouteWithChildren
  AppHelpRoute: typeof AppHelpRoute
  AppOrganizationsRoute: typeof AppOrganizationsRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppToolsRoute: typeof AppToolsRouteWithChildren
  AppIndexRoute: typeof AppIndexRoute
  AppStreamsStreamPdaRoute: typeof AppStreamsStreamPdaRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppActivityRoute: AppActivityRoute,
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppCreateRoute: AppCreateRouteWithChildren,
  AppHelpRoute: AppHelpRoute,
  AppOrganizationsRoute: AppOrganizationsRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppToolsRoute: AppToolsRouteWithChildren,
  AppIndexRoute: AppIndexRoute,
  AppStreamsStreamPdaRoute: AppStreamsStreamPdaRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  DocsRoute: DocsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
