/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ToolsRouteImport } from './routes/tools'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as OrganizationsRouteImport } from './routes/organizations'
import { Route as HelpRouteImport } from './routes/help'
import { Route as CreateRouteImport } from './routes/create'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as ActivityRouteImport } from './routes/activity'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ToolsTokensRouteImport } from './routes/tools.tokens'
import { Route as ToolsCreateTokenRouteImport } from './routes/tools.create-token'
import { Route as StreamsStreamPdaRouteImport } from './routes/streams.$streamPda'
import { Route as OrganizationsOrgIdRouteImport } from './routes/organizations.$orgId'
import { Route as CreateMilestoneRouteImport } from './routes/create.milestone'
import { Route as CreateLinearRouteImport } from './routes/create.linear'
import { Route as CreateCliffRouteImport } from './routes/create.cliff'
import { Route as ToolsCreateTokenWalletRouteImport } from './routes/tools.create-token.wallet'
import { Route as ToolsCreateTokenPlatformRouteImport } from './routes/tools.create-token.platform'
import { Route as OrganizationsOrgIdVestRouteImport } from './routes/organizations.$orgId.vest'
import { Route as OrganizationsOrgIdEditRouteImport } from './routes/organizations.$orgId.edit'
import { Route as OrganizationsOrgIdVestIndividualRouteImport } from './routes/organizations.$orgId.vest.individual'
import { Route as OrganizationsOrgIdVestAllRouteImport } from './routes/organizations.$orgId.vest.all'

const ToolsRoute = ToolsRouteImport.update({
  id: '/tools',
  path: '/tools',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsRoute = OrganizationsRouteImport.update({
  id: '/organizations',
  path: '/organizations',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateRoute = CreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivityRoute = ActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ToolsTokensRoute = ToolsTokensRouteImport.update({
  id: '/tokens',
  path: '/tokens',
  getParentRoute: () => ToolsRoute,
} as any)
const ToolsCreateTokenRoute = ToolsCreateTokenRouteImport.update({
  id: '/create-token',
  path: '/create-token',
  getParentRoute: () => ToolsRoute,
} as any)
const StreamsStreamPdaRoute = StreamsStreamPdaRouteImport.update({
  id: '/streams/$streamPda',
  path: '/streams/$streamPda',
  getParentRoute: () => rootRouteImport,
} as any)
const OrganizationsOrgIdRoute = OrganizationsOrgIdRouteImport.update({
  id: '/$orgId',
  path: '/$orgId',
  getParentRoute: () => OrganizationsRoute,
} as any)
const CreateMilestoneRoute = CreateMilestoneRouteImport.update({
  id: '/milestone',
  path: '/milestone',
  getParentRoute: () => CreateRoute,
} as any)
const CreateLinearRoute = CreateLinearRouteImport.update({
  id: '/linear',
  path: '/linear',
  getParentRoute: () => CreateRoute,
} as any)
const CreateCliffRoute = CreateCliffRouteImport.update({
  id: '/cliff',
  path: '/cliff',
  getParentRoute: () => CreateRoute,
} as any)
const ToolsCreateTokenWalletRoute = ToolsCreateTokenWalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => ToolsCreateTokenRoute,
} as any)
const ToolsCreateTokenPlatformRoute =
  ToolsCreateTokenPlatformRouteImport.update({
    id: '/platform',
    path: '/platform',
    getParentRoute: () => ToolsCreateTokenRoute,
  } as any)
const OrganizationsOrgIdVestRoute = OrganizationsOrgIdVestRouteImport.update({
  id: '/vest',
  path: '/vest',
  getParentRoute: () => OrganizationsOrgIdRoute,
} as any)
const OrganizationsOrgIdEditRoute = OrganizationsOrgIdEditRouteImport.update({
  id: '/edit',
  path: '/edit',
  getParentRoute: () => OrganizationsOrgIdRoute,
} as any)
const OrganizationsOrgIdVestIndividualRoute =
  OrganizationsOrgIdVestIndividualRouteImport.update({
    id: '/individual',
    path: '/individual',
    getParentRoute: () => OrganizationsOrgIdVestRoute,
  } as any)
const OrganizationsOrgIdVestAllRoute =
  OrganizationsOrgIdVestAllRouteImport.update({
    id: '/all',
    path: '/all',
    getParentRoute: () => OrganizationsOrgIdVestRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/create': typeof CreateRouteWithChildren
  '/help': typeof HelpRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/create/cliff': typeof CreateCliffRoute
  '/create/linear': typeof CreateLinearRoute
  '/create/milestone': typeof CreateMilestoneRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/streams/$streamPda': typeof StreamsStreamPdaRoute
  '/tools/create-token': typeof ToolsCreateTokenRouteWithChildren
  '/tools/tokens': typeof ToolsTokensRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/organizations/$orgId/vest': typeof OrganizationsOrgIdVestRouteWithChildren
  '/tools/create-token/platform': typeof ToolsCreateTokenPlatformRoute
  '/tools/create-token/wallet': typeof ToolsCreateTokenWalletRoute
  '/organizations/$orgId/vest/all': typeof OrganizationsOrgIdVestAllRoute
  '/organizations/$orgId/vest/individual': typeof OrganizationsOrgIdVestIndividualRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/create': typeof CreateRouteWithChildren
  '/help': typeof HelpRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/create/cliff': typeof CreateCliffRoute
  '/create/linear': typeof CreateLinearRoute
  '/create/milestone': typeof CreateMilestoneRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/streams/$streamPda': typeof StreamsStreamPdaRoute
  '/tools/create-token': typeof ToolsCreateTokenRouteWithChildren
  '/tools/tokens': typeof ToolsTokensRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/organizations/$orgId/vest': typeof OrganizationsOrgIdVestRouteWithChildren
  '/tools/create-token/platform': typeof ToolsCreateTokenPlatformRoute
  '/tools/create-token/wallet': typeof ToolsCreateTokenWalletRoute
  '/organizations/$orgId/vest/all': typeof OrganizationsOrgIdVestAllRoute
  '/organizations/$orgId/vest/individual': typeof OrganizationsOrgIdVestIndividualRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/activity': typeof ActivityRoute
  '/analytics': typeof AnalyticsRoute
  '/create': typeof CreateRouteWithChildren
  '/help': typeof HelpRoute
  '/organizations': typeof OrganizationsRouteWithChildren
  '/profile': typeof ProfileRoute
  '/settings': typeof SettingsRoute
  '/tools': typeof ToolsRouteWithChildren
  '/create/cliff': typeof CreateCliffRoute
  '/create/linear': typeof CreateLinearRoute
  '/create/milestone': typeof CreateMilestoneRoute
  '/organizations/$orgId': typeof OrganizationsOrgIdRouteWithChildren
  '/streams/$streamPda': typeof StreamsStreamPdaRoute
  '/tools/create-token': typeof ToolsCreateTokenRouteWithChildren
  '/tools/tokens': typeof ToolsTokensRoute
  '/organizations/$orgId/edit': typeof OrganizationsOrgIdEditRoute
  '/organizations/$orgId/vest': typeof OrganizationsOrgIdVestRouteWithChildren
  '/tools/create-token/platform': typeof ToolsCreateTokenPlatformRoute
  '/tools/create-token/wallet': typeof ToolsCreateTokenWalletRoute
  '/organizations/$orgId/vest/all': typeof OrganizationsOrgIdVestAllRoute
  '/organizations/$orgId/vest/individual': typeof OrganizationsOrgIdVestIndividualRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/activity'
    | '/analytics'
    | '/create'
    | '/help'
    | '/organizations'
    | '/profile'
    | '/settings'
    | '/tools'
    | '/create/cliff'
    | '/create/linear'
    | '/create/milestone'
    | '/organizations/$orgId'
    | '/streams/$streamPda'
    | '/tools/create-token'
    | '/tools/tokens'
    | '/organizations/$orgId/edit'
    | '/organizations/$orgId/vest'
    | '/tools/create-token/platform'
    | '/tools/create-token/wallet'
    | '/organizations/$orgId/vest/all'
    | '/organizations/$orgId/vest/individual'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/activity'
    | '/analytics'
    | '/create'
    | '/help'
    | '/organizations'
    | '/profile'
    | '/settings'
    | '/tools'
    | '/create/cliff'
    | '/create/linear'
    | '/create/milestone'
    | '/organizations/$orgId'
    | '/streams/$streamPda'
    | '/tools/create-token'
    | '/tools/tokens'
    | '/organizations/$orgId/edit'
    | '/organizations/$orgId/vest'
    | '/tools/create-token/platform'
    | '/tools/create-token/wallet'
    | '/organizations/$orgId/vest/all'
    | '/organizations/$orgId/vest/individual'
  id:
    | '__root__'
    | '/'
    | '/activity'
    | '/analytics'
    | '/create'
    | '/help'
    | '/organizations'
    | '/profile'
    | '/settings'
    | '/tools'
    | '/create/cliff'
    | '/create/linear'
    | '/create/milestone'
    | '/organizations/$orgId'
    | '/streams/$streamPda'
    | '/tools/create-token'
    | '/tools/tokens'
    | '/organizations/$orgId/edit'
    | '/organizations/$orgId/vest'
    | '/tools/create-token/platform'
    | '/tools/create-token/wallet'
    | '/organizations/$orgId/vest/all'
    | '/organizations/$orgId/vest/individual'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ActivityRoute: typeof ActivityRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CreateRoute: typeof CreateRouteWithChildren
  HelpRoute: typeof HelpRoute
  OrganizationsRoute: typeof OrganizationsRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SettingsRoute: typeof SettingsRoute
  ToolsRoute: typeof ToolsRouteWithChildren
  StreamsStreamPdaRoute: typeof StreamsStreamPdaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/tools': {
      id: '/tools'
      path: '/tools'
      fullPath: '/tools'
      preLoaderRoute: typeof ToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations': {
      id: '/organizations'
      path: '/organizations'
      fullPath: '/organizations'
      preLoaderRoute: typeof OrganizationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create': {
      id: '/create'
      path: '/create'
      fullPath: '/create'
      preLoaderRoute: typeof CreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activity': {
      id: '/activity'
      path: '/activity'
      fullPath: '/activity'
      preLoaderRoute: typeof ActivityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tools/tokens': {
      id: '/tools/tokens'
      path: '/tokens'
      fullPath: '/tools/tokens'
      preLoaderRoute: typeof ToolsTokensRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/tools/create-token': {
      id: '/tools/create-token'
      path: '/create-token'
      fullPath: '/tools/create-token'
      preLoaderRoute: typeof ToolsCreateTokenRouteImport
      parentRoute: typeof ToolsRoute
    }
    '/streams/$streamPda': {
      id: '/streams/$streamPda'
      path: '/streams/$streamPda'
      fullPath: '/streams/$streamPda'
      preLoaderRoute: typeof StreamsStreamPdaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/organizations/$orgId': {
      id: '/organizations/$orgId'
      path: '/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof OrganizationsOrgIdRouteImport
      parentRoute: typeof OrganizationsRoute
    }
    '/create/milestone': {
      id: '/create/milestone'
      path: '/milestone'
      fullPath: '/create/milestone'
      preLoaderRoute: typeof CreateMilestoneRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/linear': {
      id: '/create/linear'
      path: '/linear'
      fullPath: '/create/linear'
      preLoaderRoute: typeof CreateLinearRouteImport
      parentRoute: typeof CreateRoute
    }
    '/create/cliff': {
      id: '/create/cliff'
      path: '/cliff'
      fullPath: '/create/cliff'
      preLoaderRoute: typeof CreateCliffRouteImport
      parentRoute: typeof CreateRoute
    }
    '/tools/create-token/wallet': {
      id: '/tools/create-token/wallet'
      path: '/wallet'
      fullPath: '/tools/create-token/wallet'
      preLoaderRoute: typeof ToolsCreateTokenWalletRouteImport
      parentRoute: typeof ToolsCreateTokenRoute
    }
    '/tools/create-token/platform': {
      id: '/tools/create-token/platform'
      path: '/platform'
      fullPath: '/tools/create-token/platform'
      preLoaderRoute: typeof ToolsCreateTokenPlatformRouteImport
      parentRoute: typeof ToolsCreateTokenRoute
    }
    '/organizations/$orgId/vest': {
      id: '/organizations/$orgId/vest'
      path: '/vest'
      fullPath: '/organizations/$orgId/vest'
      preLoaderRoute: typeof OrganizationsOrgIdVestRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/organizations/$orgId/edit': {
      id: '/organizations/$orgId/edit'
      path: '/edit'
      fullPath: '/organizations/$orgId/edit'
      preLoaderRoute: typeof OrganizationsOrgIdEditRouteImport
      parentRoute: typeof OrganizationsOrgIdRoute
    }
    '/organizations/$orgId/vest/individual': {
      id: '/organizations/$orgId/vest/individual'
      path: '/individual'
      fullPath: '/organizations/$orgId/vest/individual'
      preLoaderRoute: typeof OrganizationsOrgIdVestIndividualRouteImport
      parentRoute: typeof OrganizationsOrgIdVestRoute
    }
    '/organizations/$orgId/vest/all': {
      id: '/organizations/$orgId/vest/all'
      path: '/all'
      fullPath: '/organizations/$orgId/vest/all'
      preLoaderRoute: typeof OrganizationsOrgIdVestAllRouteImport
      parentRoute: typeof OrganizationsOrgIdVestRoute
    }
  }
}

interface CreateRouteChildren {
  CreateCliffRoute: typeof CreateCliffRoute
  CreateLinearRoute: typeof CreateLinearRoute
  CreateMilestoneRoute: typeof CreateMilestoneRoute
}

const CreateRouteChildren: CreateRouteChildren = {
  CreateCliffRoute: CreateCliffRoute,
  CreateLinearRoute: CreateLinearRoute,
  CreateMilestoneRoute: CreateMilestoneRoute,
}

const CreateRouteWithChildren =
  CreateRoute._addFileChildren(CreateRouteChildren)

interface OrganizationsOrgIdVestRouteChildren {
  OrganizationsOrgIdVestAllRoute: typeof OrganizationsOrgIdVestAllRoute
  OrganizationsOrgIdVestIndividualRoute: typeof OrganizationsOrgIdVestIndividualRoute
}

const OrganizationsOrgIdVestRouteChildren: OrganizationsOrgIdVestRouteChildren =
  {
    OrganizationsOrgIdVestAllRoute: OrganizationsOrgIdVestAllRoute,
    OrganizationsOrgIdVestIndividualRoute:
      OrganizationsOrgIdVestIndividualRoute,
  }

const OrganizationsOrgIdVestRouteWithChildren =
  OrganizationsOrgIdVestRoute._addFileChildren(
    OrganizationsOrgIdVestRouteChildren,
  )

interface OrganizationsOrgIdRouteChildren {
  OrganizationsOrgIdEditRoute: typeof OrganizationsOrgIdEditRoute
  OrganizationsOrgIdVestRoute: typeof OrganizationsOrgIdVestRouteWithChildren
}

const OrganizationsOrgIdRouteChildren: OrganizationsOrgIdRouteChildren = {
  OrganizationsOrgIdEditRoute: OrganizationsOrgIdEditRoute,
  OrganizationsOrgIdVestRoute: OrganizationsOrgIdVestRouteWithChildren,
}

const OrganizationsOrgIdRouteWithChildren =
  OrganizationsOrgIdRoute._addFileChildren(OrganizationsOrgIdRouteChildren)

interface OrganizationsRouteChildren {
  OrganizationsOrgIdRoute: typeof OrganizationsOrgIdRouteWithChildren
}

const OrganizationsRouteChildren: OrganizationsRouteChildren = {
  OrganizationsOrgIdRoute: OrganizationsOrgIdRouteWithChildren,
}

const OrganizationsRouteWithChildren = OrganizationsRoute._addFileChildren(
  OrganizationsRouteChildren,
)

interface ToolsCreateTokenRouteChildren {
  ToolsCreateTokenPlatformRoute: typeof ToolsCreateTokenPlatformRoute
  ToolsCreateTokenWalletRoute: typeof ToolsCreateTokenWalletRoute
}

const ToolsCreateTokenRouteChildren: ToolsCreateTokenRouteChildren = {
  ToolsCreateTokenPlatformRoute: ToolsCreateTokenPlatformRoute,
  ToolsCreateTokenWalletRoute: ToolsCreateTokenWalletRoute,
}

const ToolsCreateTokenRouteWithChildren =
  ToolsCreateTokenRoute._addFileChildren(ToolsCreateTokenRouteChildren)

interface ToolsRouteChildren {
  ToolsCreateTokenRoute: typeof ToolsCreateTokenRouteWithChildren
  ToolsTokensRoute: typeof ToolsTokensRoute
}

const ToolsRouteChildren: ToolsRouteChildren = {
  ToolsCreateTokenRoute: ToolsCreateTokenRouteWithChildren,
  ToolsTokensRoute: ToolsTokensRoute,
}

const ToolsRouteWithChildren = ToolsRoute._addFileChildren(ToolsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ActivityRoute: ActivityRoute,
  AnalyticsRoute: AnalyticsRoute,
  CreateRoute: CreateRouteWithChildren,
  HelpRoute: HelpRoute,
  OrganizationsRoute: OrganizationsRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SettingsRoute: SettingsRoute,
  ToolsRoute: ToolsRouteWithChildren,
  StreamsStreamPdaRoute: StreamsStreamPdaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
