name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  format:
    uses: ./.github/workflows/format.yaml
  lint:
    uses: ./.github/workflows/lint.yaml
  lint-rust:
    uses: ./.github/workflows/rust-lint.yaml
  typecheck-sdk:
    uses: ./.github/workflows/typecheck-sdk.yaml
  typecheck-api:
    uses: ./.github/workflows/typecheck-api.yaml
  typecheck-web:
    uses: ./.github/workflows/typecheck-web.yaml
  typecheck-anchor:
    uses: ./.github/workflows/typecheck-anchor.yaml
  build-web:
    uses: ./.github/workflows/build-web.yaml
  test-api:
    uses: ./.github/workflows/test-api.yaml
  test-web:
    uses: ./.github/workflows/test-web.yaml
  test-storybook:
    uses: ./.github/workflows/test-storybook.yaml
  typecheck-docs:
    uses: ./.github/workflows/typecheck-docs.yaml
  anchor:
    uses: ./.github/workflows/anchor.yaml

  deploy-api:
    if: github.event_name == 'push'
    needs:
      - typecheck-api
      - test-api
    uses: ./.github/workflows/deploy-api.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-web:
    if: github.event_name == 'push'
    needs:
      - typecheck-web
      - test-web
      - build-web
    uses: ./.github/workflows/deploy-web.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-docs:
    if: github.event_name == 'push'
    needs:
      - typecheck-docs
    uses: ./.github/workflows/deploy-docs.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

  deploy-storybook:
    if: github.event_name == 'push'
    needs:
      - test-storybook
    uses: ./.github/workflows/deploy-storybook.yaml
    secrets:
      CF_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      CF_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
