name: Test Web

on:
  workflow_call:

jobs:
  test-web:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v6
      - uses: ./.github/actions/pnpm-setup
      - name: Build SDK
        run: pnpm --filter @solana-tdp/sdk build
      - name: Run unit tests
        run: pnpm --filter @solana-tdp/web test
